name = "apnapal-worker"
main = "src/index.ts"
compatibility_date = "2026-04-10"
compatibility_flags = ["nodejs_compat"]

[observability]
[observability.logs]
enabled = false
invocation_logs = true

[observability.traces]
enabled = false

[vars]
SUPABASE_URL = "https://usqxntcnfkjbzhvaerfi.supabase.co"

